cmake_minimum_required(VERSION 2.8.3)
project(smartcar_region_tool)
find_package(catkin REQUIRED COMPONENTS rviz pluginlib)
find_package(Qt5 REQUIRED COMPONENTS Widgets)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -fPIC")
catkin_package(LIBRARIES smartcar_region_tool)
include_directories(${catkin_INCLUDE_DIRS})
add_library(smartcar_region_tool src.cpp)
target_link_libraries(smartcar_region_tool ${catkin_LIBRARIES} Qt5::Widgets)
install(TARGETS smartcar_region_tool LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION})
install(FILES plugin_description.xml DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
